#!/usr/bin/env python3
"""Rebuild the website's derived data files from the results CSVs.

The CSV files in the root of this repository are the source of truth. Two
parts of the website need a smaller, pre-computed view of them:

  assets/data/results-by-age/<year>.json
      [finish time in seconds, age] for every man and woman who finished in
      under seven hours. Feeds the "Results by Age & Gender" scatter chart on
      the Performance tab.

  assets/data/finish-times.json
      Every finish time for each year, sorted and delta-encoded. Feeds the
      placement calculator.

Run this after changing any results CSV for the years listed in YEARS:

    python3 tools/build_site_data.py

It needs nothing beyond the Python 3 standard library. (The Results tab reads
the CSV files directly, so it never needs a rebuild.)
"""
import csv
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'assets', 'data')

# Years with age and gender for the full field.
YEARS = range(2000, 2020)

# The scatter chart leaves out anyone slower than seven hours.
SCATTER_CUTOFF_SECONDS = 25200


def read_results(year):
    """Yield one dict per finisher from results<year>.csv.

    The files are MySQL exports: every text field is double-quoted, a quote
    inside a field is written as \\" and a missing value is a bare NULL.
    """
    path = os.path.join(ROOT, 'results%d.csv' % year)
    with open(path, newline='', encoding='utf-8') as handle:
        reader = csv.reader(handle, quotechar='"', escapechar='\\',
                            doublequote=False)
        header = next(reader)
        for row in reader:
            if len(row) != len(header):
                continue
            yield dict(zip(header, row))


def to_int(value):
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def delta_encode(sorted_values):
    previous = 0
    deltas = []
    for value in sorted_values:
        deltas.append(value - previous)
        previous = value
    return deltas


def write_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as handle:
        json.dump(data, handle, separators=(',', ':'))
        handle.write('\n')


def main():
    finish_times = {}
    for year in YEARS:
        scatter = {'males': [], 'females': []}
        times = {'M': [], 'F': [], 'other': []}
        for row in read_results(year):
            seconds = to_int(row.get('seconds'))
            if seconds is None:
                continue
            gender = (row.get('gender') or '').upper()
            age = to_int(row.get('age')) or 0
            if seconds < SCATTER_CUTOFF_SECONDS:
                if gender == 'M':
                    scatter['males'].append([seconds, age])
                elif gender == 'F':
                    scatter['females'].append([seconds, age])
            if seconds > 0:
                times[gender if gender in ('M', 'F') else 'other'].append(seconds)
        write_json(os.path.join(OUT, 'results-by-age', '%d.json' % year), scatter)
        finish_times[str(year)] = {
            key: delta_encode(sorted(values)) for key, values in times.items()
        }
        print('%d: %d men, %d women, %d other' % (
            year, len(times['M']), len(times['F']), len(times['other'])))

    write_json(os.path.join(OUT, 'finish-times.json'), {
        'about': 'Finish times in seconds per year, sorted ascending and '
                 'delta-encoded (each value is the gap to the previous one). '
                 'Generated by tools/build_site_data.py.',
        'years': finish_times,
    })


if __name__ == '__main__':
    main()
